name: Copilot Improve Artwork

on:
  issues:
    types: [assigned]

jobs:
  copilot-improve-artwork:
    runs-on: ubuntu-latest
    # Only run if the issue is assigned to the Copilot agent
    if: contains(github.event.issue.assignees.*.login, 'Copilot')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Copilot artwork improvement script
      run: node copilot-improve-artwork.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        
    - name: Build project to validate changes
      run: npm run build
      
    - name: Commit and push changes
      run: |
        git config --local user.email "copilot@github.com"
        git config --local user.name "GitHub Copilot"
        git add src/artwork-state.ts
        git commit -m "Copilot artwork improvement - Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}" || exit 0
        git push
        
    - name: Comment on issue
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const content = fs.readFileSync('src/artwork-state.ts', 'utf8');
          const match = content.match(/"generation": (\d+)/);
          const generation = match ? match[1] : "unknown";
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🎨 **Artwork improved by Copilot!**\n\nI've analyzed the current artwork and applied intelligent improvements. The artwork is now at generation ${generation}.\n\nChanges have been automatically committed and the artwork will be visible on the live site.`
          });